name: Download custom JDK
description: Download the custom JDK used for AOT cache workflows
runs:
  using: composite
  steps:
    - name: Download custom JDK
      shell: bash
      run: |
        curl -L -o jdk-custom.tar.gz \
          "https://github.com/algomaster99/jdk/releases/download/jdk-supply-chain-aotcache-da030d5c04f/jdk-supply-chain-aotcache-da030d5c04f.tar.gz"
